version: "3.8"

services:
  java_app:
    build:
      context: .
    container_name: "expensesapp"
    networks:
      - expenses-app-nw
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/expenses_tracker?allowPublicKeyRetrieval=true&useSSL=false"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "Test@123"
    depends_on:
      - mysql_db
    ports:
      - "9090:8080"
    restart: always

  mysql_db:
    image: mysql
    container_name: "mysql"
    networks:
      - expenses-app-nw
    environment:
      MYSQL_ROOT_PASSWORD: "Test@123"
      MYSQL_DATABASE: "expenses_tracker"
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-uroot","-pTest@123"]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 5s
    volumes:
      - ./mysql-data:/var/lib/mysql

networks:
  expenses-app-nw:

volumes:
  mysql-data:
