apiVersion: v1
kind: Service
metadata:
  name: expensesapp
  namespace: expenses
spec:
  selector:
    app: expensesapp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort

