apiVersion: apps/v1
kind: Deployment
metadata:
  name: expensesapp
  namespace: expenses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expensesapp
  template:
    metadata:
      labels:
        app: expensesapp
    spec:
      containers:
        - name: expensesapp
          image: vasu049/expense-tracker:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/expenses_tracker?allowPublicKeyRetrieval=true&useSSL=false"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "Test@123"

